"""Update Initial Migration - Venue model

Revision ID: 1437b0b195f4
Revises: d197f7dddebe
Create Date: 2022-05-28 23:26:50.092862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1437b0b195f4'
down_revision = 'd197f7dddebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.PickleType(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
